In [11]:
x = 2
type(x)

int

In [13]:
if x > 18:
    print('adult')
else :
    print('kid')

kid

In [17]:
for i in range(x):
    print(i)

0
1

In [24]:
def green(num):
    return 'boom ' + num

print(green('44'))

boom 44

In [1]:
x = 4
4%2 == 0

True

In [3]:
x = 2
print(x/4)

0.5

In [6]:
x = 3
if x % 3 == 1:
    print('here it is 3')
else:
    print('nothing')

nothing

In [14]:
# practice on dataframe
import pandas as pd

data = {
    'group': ['fruit', 'fruit', 'fruit', 'vegetable', 'vegetable', 'vegetable'],
    'name': ['apple', 'banana', 'orange', 'broccoli', 'kale', 'lettuce'],
    'count': [90, 150, 130, 80, 70, 125]
}
dt = {
    'hello':'green'
}
print(data)
df = pd.DataFrame(data)
print(df)

{'group': ['fruit', 'fruit', 'fruit', 'vegetable', 'vegetable', 'vegetable'], 'name': ['apple', 'banana', 'orange', 'broccoli', 'kale', 'lettuce'], 'count': [90, 150, 130, 80, 70, 125]}
       group      name  count
0      fruit     apple     90
1      fruit    banana    150
2      fruit    orange    130
3  vegetable  broccoli     80
4  vegetable      kale     70
5  vegetable   lettuce    125

In [15]:
print(df['group'])

0        fruit
1        fruit
2        fruit
3    vegetable
4    vegetable
5    vegetable
Name: group, dtype: str

In [18]:
df[df['count'] > 100]

       group     name  count
1      fruit   banana    150
2      fruit   orange    130
5  vegetable  lettuce    125

In [20]:
datacamp = {
    'course': 'python',
    'level': 'intermediate',
    'lesson': {
        'dictionaries': 'python',
        'lists': 'something'
    }
}

datacamp['lesson']['list1'] = 'list 1'
pd.DataFrame(datacamp)

              course         level     lesson
dictionaries  python  intermediate     python
lists         python  intermediate  something
list1         python  intermediate     list 1